I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    Narration "* 睜開眼睛後第一個看到的，是黑白色的花。"
  File "game/script.rpy", line 10, in general
    renpy.wait(0.2)  # 等待 0.2 秒
AttributeError: module 'renpy.exports' has no attribute 'wait'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script
    Narration "* 睜開眼睛後第一個看到的，是黑白色的花。"
  File "D:\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "D:\renpy-8.3.2-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.3.2-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "D:\renpy-8.3.2-sdk\renpy\character.py", line 1455, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\renpy-8.3.2-sdk\renpy\character.py", line 1106, in do_display
    display_say(who,
  File "D:\renpy-8.3.2-sdk\renpy\character.py", line 797, in display_say
    pause_callback("show_done")
  File "D:\renpy-8.3.2-sdk\renpy\character.py", line 91, in __call__
    c(*args, **kwargs)
  File "game/script.rpy", line 10, in general
    renpy.wait(0.2)  # 等待 0.2 秒
AttributeError: module 'renpy.exports' has no attribute 'wait'

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
Greytale 1.0
Wed Nov 13 22:41:53 2024
