I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 52, in script
    define config.default_volume = {
  File "game/options.rpy", line 52, in script
    define config.default_volume = {
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.default_volume is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.3.2-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.3.2-sdk\renpy\main.py", line 541, in main
    renpy.game.context().run(node)
  File "game/options.rpy", line 52, in script
    define config.default_volume = {
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/options.rpy", line 52, in script
    define config.default_volume = {
  File "D:\renpy-8.3.2-sdk\renpy\ast.py", line 2235, in execute
    self.set()
  File "D:\renpy-8.3.2-sdk\renpy\ast.py", line 2253, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "D:\renpy-8.3.2-sdk\renpy\defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.default_volume is not a known configuration variable.

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
Greytale 1.0
Fri Nov 22 22:29:26 2024
